### ISSUE TITLE
Visor de datos (2.11

### ISSUE THREAD

**Issue by sarudego** [sarudego/catmdedit-vv#6]
No está disponible en el sistema probado.

**Comment by sarudego** [comment]
Se podría revisar el código e implementarlo, pero no se va a realizar por el coste que conlleva.

**Comment by miguel-latre** [comment]
1. Este defecto no está documentado en la hoja de pruebas de la práctica 1.ª.
2. No tiene sentido etiquetarlo a la vez como «bug» y «enhancement». Se trata de un _bug_.
3. La etiqueta «invalid» implicaría que el _issue_ en sí mismo es un error. La etiquteta correcta respecto al estado de resolución al cerrarlo sería la de «wontfix».
