### ISSUE TITLE
Existencia de tesauros (4.1)

### ISSUE THREAD

**Issue by sarudego** [sarudego/catmdedit-vv#7]
No existen tesauros, no aparece el menú.

/cc @sarudego

**Comment by sarudego** [comment]
Es necesario revisar el código, no se va a arreglar.

**Comment by miguel-latre** [comment]
Al final, este _issue_ sí que sería uno que podría cerrarse como «invalid» en lugar de «wontfix». La causa es que no hay ninguna opción de menú para los tesauros. Se accede a ellos desde la ventana de edición de metadatos.
